# Generated by Django 4.2.5 on 2024-06-01 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kucing_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penyakit',
            name='gambar',
        ),
    ]
