# Generated by Django 4.2.5 on 2024-07-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kucing_app', '0002_remove_penyakit_gambar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basispengetahuan',
            old_name='kode_gejala',
            new_name='id_gejala',
        ),
        migrations.RenameField(
            model_name='basispengetahuan',
            old_name='kode_penyakit',
            new_name='id_penyakit',
        ),
    ]
