# Generated by Django 4.2.5 on 2024-08-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kucing_app', '0003_rename_kode_gejala_basispengetahuan_id_gejala_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riwayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=244)),
                ('tgl', models.DateTimeField()),
                ('result', models.TextField()),
            ],
        ),
    ]
