# Generated by Django 4.2.5 on 2024-08-20 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kucing_app', '0004_riwayat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DsRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot', models.FloatField()),
                ('id_gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucing_app.gejala')),
                ('id_penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucing_app.penyakit')),
            ],
        ),
    ]
